version: "3.7"

services:

  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app

  php:
    image: test_backend_php
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: dev
      args:
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST:-172.17.0.1}
        - DB_SERVER=mysql
        - DB_PORT=3306
        - DB_NAME=app
        - DB_USER=root
        - DB_PASSWORD=root
    ports:
      - 9000
    volumes:
      - ./api:/app
    environment:
      - PHP_IDE_CONFIG=serverName=${XDEBUG_IDE_SERVERNAME:-php}
    depends_on:
      - mysql

  nginx:
    image: test_backend_nginx
    build:
      context: ./api
      dockerfile: ./docker/nginx/Dockerfile
    links:
      - php
    volumes:
      - "./api/public:/var/www/app/public"
    ports:
      - 8080:80
      - 444:443
    environment:
      - API_HOST=php
      - API_PORT=9000