<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxRYP75\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxRYP75/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxRYP75.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxRYP75\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZxRYP75\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZxRYP75',
    'container.build_id' => 'db5a5b89',
    'container.build_time' => 1637615267,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxRYP75');
